# Generated by Django 5.1.6 on 2025-03-27 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0007_county_alter_address_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='County',
            new_name='Country',
        ),
    ]
